"""Now added stages question can be group by stages with many to many relationship.

Revision ID: 50efd8cd0de9
Revises: 5f5ad9313245
Create Date: 2025-02-24 14:17:44.436631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50efd8cd0de9'
down_revision = '5f5ad9313245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_username_key', ['username'])

    # ### end Alembic commands ###
