"""Initial migration

Revision ID: 819196689cdc
Revises: 
Create Date: 2025-02-23 13:03:20.700159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819196689cdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('email_address', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('TEACHER', 'STUDENT', 'ADMIN', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('username')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=512), nullable=False),
    sa.Column('answer_text', sa.String(length=256), nullable=False),
    sa.Column('answer_explained', sa.String(length=256), nullable=True),
    sa.Column('question_type', sa.Boolean(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_text')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('num_questions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quizzes_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_options', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_options_question_id'), ['question_id'], unique=False)

    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_provided', sa.String(length=16), nullable=False),
    sa.Column('time_taken', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_questions_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_questions_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('quiz_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_questions_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=128), nullable=False),
    sa.Column('taken_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_questions_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_result_quiz_questions_id'), ['quiz_questions_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_result_student_id'), ['student_id'], unique=False)

    op.create_table('student_quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('quiz_result_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['quiz_result_id'], ['quiz_result.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_quizzes_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_quizzes_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_quizzes_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_quizzes_quiz_id'))

    op.drop_table('student_quizzes')
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_result_student_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_result_quiz_questions_id'))

    op.drop_table('quiz_result')
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_quiz_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_questions_question_id'))

    op.drop_table('quiz_questions')
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_options_question_id'))

    op.drop_table('options')
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quizzes_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_quizzes_subject_id'))

    op.drop_table('quizzes')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_questions_subject_id'))

    op.drop_table('questions')
    op.drop_table('users')
    op.drop_table('subjects')
    # ### end Alembic commands ###
